### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/Nagoya#100]
### Current State
Currently, stories do not support pagination. As we add more and more stories, a pagination feature may be desired.

Hugo supports pagination for section pages, so we may have to consider converting topics to list bundles, and converting the stories to leaf bundles. See https://gohugo.io/templates/pagination/

### TODO
- [ ] Investigate Hugo pagination
- [ ] If necessary, restructure topics and stories to enable pagination
- [ ] Implement pagination on stories
