### ISSUE TITLE
Adjust Project Naming

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/Nagoya#84]
### Current State
Following the sync, the project scope will prioritize this dataset visualizer for the Bolivia dataset specifically. The current project is in a hybrid state of purely just supporting the Bolivia dataset, with naming/documentation on supporting multiple. 

### TODO
- [x] - Change Netlify deployment name
- [x] - Fix README deployment 
- [x] - Adjust documentation
- [x] - Adjust naming of certain paragraphs from a more generalized format to one aimed at the Bolivia dataset
- [x] - Adjust and fix any artifacts related to this change

**Comment by GeoffreyXue** [comment]
Changing naming convention to QuaRCS Bolivia.
