### ISSUE TITLE
Redundant Shortcode Removal

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/Nagoya#94]
### Current State
After #87 and #92, the majority of the shortcode formatting can be removed in favor of just using plain Markdown files. There exists a lot of redundant shortcodes that don't bring any customizable benefit for stories.

### TODO
- [x] Migrate existing stories over to not use the shortcode
- [x] Remove shortcodes themselves, as well as their related files (css classes)
- [x] Update documentation to remove shortcode reference

**Comment by GeoffreyXue** [comment]
As part of this TODO, updating story file to be `story.md` instead of `index.md`, as it currently doesn't represent a leaf bundle.
