### ISSUE TITLE
Update old link methodology

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/Nagoya#99]
### Current State
With #96, we now can support an unlimited number of links for stories. However, we still have the old "deepnote" annotation that can be replaced with the new links front matter.

```
-----
deepnote: "link"
-----
```
to 
```
-----
links: 
    deepnote: "link"
-----
```
 
### TODO
- [ ] Add original deepnote links in new link format, verify they're good
- [ ] Remove deepnote front matter parameter
- [ ] Remove check for deepnote parameter in `layouts/topic/single.html`
